// Cozy-Integration Phase 1: Basiszutaten vereinheitlichen
// Kanonisches Item ersetzt Duplikate in allen Rezepten; Umtausch-Rezepte für Alt-Items.
ServerEvents.recipes(event => {
  event.replaceInput({not: {id: /^cozy:/}}, 'create:dough', 'farmersdelight:wheat_dough')
  event.replaceOutput({not: {id: /^cozy:/}}, 'create:dough', 'farmersdelight:wheat_dough')
  event.shapeless('farmersdelight:wheat_dough', ['create:dough']).id('cozy:unify/create_dough')
  event.replaceInput({not: {id: /^cozy:/}}, 'farm_and_charm:dough', 'farmersdelight:wheat_dough')
  event.replaceOutput({not: {id: /^cozy:/}}, 'farm_and_charm:dough', 'farmersdelight:wheat_dough')
  event.shapeless('farmersdelight:wheat_dough', ['farm_and_charm:dough']).id('cozy:unify/farm_and_charm_dough')
  event.replaceInput({not: {id: /^cozy:/}}, 'pamhc2foodcore:doughitem', 'farmersdelight:wheat_dough')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pamhc2foodcore:doughitem', 'farmersdelight:wheat_dough')
  event.shapeless('farmersdelight:wheat_dough', ['pamhc2foodcore:doughitem']).id('cozy:unify/pamhc2foodcore_doughitem')
  event.replaceInput({not: {id: /^cozy:/}}, 'pamhc2foodcore:flouritem', 'create:wheat_flour')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pamhc2foodcore:flouritem', 'create:wheat_flour')
  event.shapeless('create:wheat_flour', ['pamhc2foodcore:flouritem']).id('cozy:unify/pamhc2foodcore_flouritem')
  event.replaceInput({not: {id: /^cozy:/}}, 'farm_and_charm:flour', 'create:wheat_flour')
  event.replaceOutput({not: {id: /^cozy:/}}, 'farm_and_charm:flour', 'create:wheat_flour')
  event.shapeless('create:wheat_flour', ['farm_and_charm:flour']).id('cozy:unify/farm_and_charm_flour')
  event.replaceInput({not: {id: /^cozy:/}}, 'bountifulfares:flour', 'create:wheat_flour')
  event.replaceOutput({not: {id: /^cozy:/}}, 'bountifulfares:flour', 'create:wheat_flour')
  event.shapeless('create:wheat_flour', ['bountifulfares:flour']).id('cozy:unify/bountifulfares_flour')
  event.replaceInput({not: {id: /^cozy:/}}, 'pamhc2foodcore:cheeseitem', 'brewinandchewin:flaxen_cheese_wedge')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pamhc2foodcore:cheeseitem', 'brewinandchewin:flaxen_cheese_wedge')
  event.shapeless('brewinandchewin:flaxen_cheese_wedge', ['pamhc2foodcore:cheeseitem']).id('cozy:unify/pamhc2foodcore_cheeseitem')
  event.replaceInput({not: {id: /^cozy:/}}, 'extradelight:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.replaceOutput({not: {id: /^cozy:/}}, 'extradelight:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.shapeless('brewinandchewin:flaxen_cheese_wedge', ['extradelight:cheese']).id('cozy:unify/extradelight_cheese')
  event.replaceInput({not: {id: /^cozy:/}}, 'create_bic_bit:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.replaceOutput({not: {id: /^cozy:/}}, 'create_bic_bit:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.shapeless('brewinandchewin:flaxen_cheese_wedge', ['create_bic_bit:cheese']).id('cozy:unify/create_bic_bit_cheese')
  event.replaceInput({not: {id: /^cozy:/}}, 'pizzadelight:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pizzadelight:cheese', 'brewinandchewin:flaxen_cheese_wedge')
  event.shapeless('brewinandchewin:flaxen_cheese_wedge', ['pizzadelight:cheese']).id('cozy:unify/pizzadelight_cheese')
  event.replaceInput({not: {id: /^cozy:/}}, 'pizzadelight:cheese_slice', 'expandeddelight:cheese_slice')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pizzadelight:cheese_slice', 'expandeddelight:cheese_slice')
  event.shapeless('expandeddelight:cheese_slice', ['pizzadelight:cheese_slice']).id('cozy:unify/pizzadelight_cheese_slice')
  event.replaceInput({not: {id: /^cozy:/}}, 'farm_and_charm:butter', 'extradelight:butter')
  event.replaceOutput({not: {id: /^cozy:/}}, 'farm_and_charm:butter', 'extradelight:butter')
  event.shapeless('extradelight:butter', ['farm_and_charm:butter']).id('cozy:unify/farm_and_charm_butter')
  event.replaceInput({not: {id: /^cozy:/}}, 'pamhc2foodcore:butteritem', 'extradelight:butter')
  event.replaceOutput({not: {id: /^cozy:/}}, 'pamhc2foodcore:butteritem', 'extradelight:butter')
  event.shapeless('extradelight:butter', ['pamhc2foodcore:butteritem']).id('cozy:unify/pamhc2foodcore_butteritem')
  event.replaceInput({not: {id: /^cozy:/}}, 'ratatouille:salt', 'expandeddelight:salt')
  event.replaceOutput({not: {id: /^cozy:/}}, 'ratatouille:salt', 'expandeddelight:salt')
  event.shapeless('expandeddelight:salt', ['ratatouille:salt']).id('cozy:unify/ratatouille_salt')
  event.replaceInput({not: {id: /^cozy:/}}, 'meadow:alpine_salt', 'expandeddelight:salt')
  event.replaceOutput({not: {id: /^cozy:/}}, 'meadow:alpine_salt', 'expandeddelight:salt')
  event.shapeless('expandeddelight:salt', ['meadow:alpine_salt']).id('cozy:unify/meadow_alpine_salt')
  event.replaceInput({not: {id: /^cozy:/}}, 'garnished:crushed_salt', 'expandeddelight:salt')
  event.replaceOutput({not: {id: /^cozy:/}}, 'garnished:crushed_salt', 'expandeddelight:salt')
  event.shapeless('expandeddelight:salt', ['garnished:crushed_salt']).id('cozy:unify/garnished_crushed_salt')
})
