name = "Cozy Farming SMP"
author = "Michael"
version = "0.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fca2621338c5495d0a5e3085933bba38dc8eaa91c6a7dce8deb6dd990bfff0ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
