name = "Cozy Farming SMP"
author = "Michael"
version = "0.10.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a12ee79f9e4d2c710403544d38a5e72fe1fa0f247811853c62a1d7ed62e552e0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
